requires-python = ">=3.12"
[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "ruff>=0.14.2",
]

[tool.ruff]
line-length = 79
target-version = 'py312'

[tool.ruff.lint]
fixable = ['ALL']
select = ['E', 'F', 'I', 'B', 'Q']
ignore = ['E101', "B008"]

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"

[tool.mypy]
python_version = '3.12'
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true

[tool.pytest.ini_options]
testpaths = ['tests']
pythonpath = ['src/']
